# Generated by Django 4.1.7 on 2023-03-04 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_sensitivity', models.IntegerField()),
                ('driver_impedance', models.IntegerField()),
                ('frequency_range', models.CharField(max_length=100)),
                ('drivers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.IntegerField()),
                ('wireless_charging', models.BooleanField(default=False)),
                ('charging_time', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('img', models.ImageField(blank=True, upload_to='img/category')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Characteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.audiospecification')),
                ('battery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.battery')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Wire', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DriverType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Dynamic', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=150, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(blank=True, upload_to='img/%Y/%m/%d/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.categories')),
                ('characteristics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.characteristics')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='img/%Y/%m/%d/', verbose_name='img')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.types'),
        ),
        migrations.CreateModel(
            name='Physical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collapsible', models.BooleanField(default=True)),
                ('water_resistance', models.BooleanField(default=False)),
                ('charging_time', models.DecimalField(decimal_places=1, max_digits=2)),
                ('weight', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.color')),
            ],
        ),
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote', models.BooleanField(default=True)),
                ('microphone', models.BooleanField(default=True)),
                ('noise_cancellation', models.BooleanField(default=False)),
                ('connectivity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.connectivity')),
            ],
        ),
        migrations.AddField(
            model_name='characteristics',
            name='connectivity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.connectivity'),
        ),
        migrations.AddField(
            model_name='characteristics',
            name='physical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.physical'),
        ),
        migrations.AddField(
            model_name='audiospecification',
            name='deriver_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.drivertype'),
        ),
    ]
