# Generated by Django 4.1.7 on 2023-05-25 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_cart_alter_product_id_alter_product_photo_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("670537a6-31f8-4bd3-a9d1-a37f35147c31"),
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
